### ISSUE TITLE
[RC 8 - Build 91] java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by EmanYm** [Syrent/SayanVanish#311]
Not sure if this will help with development.  I got this during my most recent update and restart.

https://www.toptal.com/developers/hastebin
Edit: I don't know why this didn't copy the paste link...

Purpur 1.20.6-2206

Full latest.log and plugin list can be provided if requested.

**Comment by EmanYm** [comment]
I get this even with v1.0.0-rc.7-4131e8c

**Comment by Syrent** [comment]
Use `/sayanvanish paste` and send paste url here

**Comment by EmanYm** [comment]
That command does not work, since SayanVanish does not even load
https://hastebin.com/share/ehigejuhic.vbnet

In-game it doesn't exist
in console it gives me

> 03.06 22:11:43 [Multicraft] Eiple ran command: sayanvanish paste
> 03.06 22:11:43 [Server] INFO Unknown or incomplete command, see below for error
> 03.06 22:11:43 [Server] INFO sayanvanish paste<--[HERE]

**Comment by Syrent** [comment]
There were a few issues with version 1.20.6. I managed to resolve most of them, particularly the packet-related problems. However, there's still an issue with the command system due to the recent changes in the Paper command system in 1.20.6. 

The simple fix would be to use the Paper 1.20.6 API, but this would require forcing Java 21 for SayanVanish on all versions, which isn't ideal. I'm working on finding a workaround to fix this problem. Until then, SayanVanish does not support version 1.20.6.

**Comment by EmanYm** [comment]
I can disable it for now.  So far only my lobby is on 1.20.6 and most of the back end servers are on 1.20.1 and up.
I'll be watching the project for updatesw!  I appreciate you, Syrent

**Comment by Syrent** [comment]
Added support for 1.20.6
https://hangar.papermc.io/Syrent/SayanVanish/versions/1.0.0-rc.9-SNAPSHOT

**Comment by EmanYm** [comment]
I switched the RC7 out with the RC9 you linked
I am getting [this error](https://hastebin.com/share/ucirabinol.ruby) during start up.
I thought that renaming the folder to "SayanVanish-backup" and letting it generate new configs would help, but I still get the same Task #439 exception
