### ISSUE TITLE
[Request] Support for ampersand

### ISSUE THREAD

**Issue by BalazsManus** [Syrent/SayanVanish#331]
For text coloring we use &#ffffff (hex) and &a (minecraft color code)
It would be great for the plugin to support them

![image](https://github.com/user-attachments/assets/64bb7e43-08a3-49c3-991e-4d22db614a1a)

**Comment by Syrent** [comment]
SayanVanish primarily uses the MiniMessage format for color coding. While it's possible to enable ampersand as a secondary option, using both formats simultaneously can lead to unexpected behavior in certain scenarios and cause performance issues. Another approach would be to let users choose between ampersand and MiniMessage formats, but since all default messages in the plugin are written using MiniMessage, I don't want to create an additional default language file for ampersand.

I recognize the challenges of using a MiniMessage-exclusive format, especially regarding compatibility with other plugins like chat, scoreboard, or tab plugins. However, I've chosen to support MiniMessage exclusively. You can still use MiniMessage-compatible plugins like FairyChat on your server, but I understand if these options don't fully meet your needs.
